In [26]:
from numpy import random
import numpy as np
import sys

x = random.rand(10, 5, 2)
xbytes = []
for idx, values in enumerate(x):
        np.append(xbytes, values.tobytes())
backtonormal = []        
for idx, values in enumerate(x):
        np.append(backtonormal, np.frombuffer(values, dtype=np.float64))

print(x)
print(xbytes)
print(backtonormal)
# As can be seen, the backtonormal form is no 100% correct. 
# Though there has to be a way so achieve this...

[[[0.47972049 0.61471393]
  [0.55846799 0.22179652]
  [0.61547104 0.62511395]
  [0.36211857 0.83706732]
  [0.15750313 0.57762529]]

 [[0.28321983 0.7810486 ]
  [0.63093629 0.14218002]
  [0.07573106 0.59070271]
  [0.01428506 0.0539787 ]
  [0.61726616 0.45758525]]

 [[0.88275714 0.95592718]
  [0.75318947 0.81471038]
  [0.22585879 0.04826557]
  [0.68386455 0.41105258]
  [0.7281388  0.58208771]]

 [[0.13718477 0.91038851]
  [0.00240406 0.06832701]
  [0.58835483 0.483766  ]
  [0.69930515 0.58513438]
  [0.97334232 0.90773404]]

 [[0.91492671 0.28108859]
  [0.31357514 0.89351343]
  [0.54220406 0.43306564]
  [0.59392526 0.67642409]
  [0.84332971 0.92222594]]

 [[0.33661853 0.98967265]
  [0.7274271  0.13871582]
  [0.22450397 0.26406155]
  [0.89310765 0.10625057]
  [0.87021708 0.87522646]]

 [[0.5791995  0.31875261]
  [0.15777188 0.61372788]
  [0.9105073  0.63226   ]
  [0.71573856 0.00904814]
  [0.92208902 0.53254308]]

 [[0.25121543 0.48560661]
  [0.05273857 0.37787798]
  [0.77729854 0.90592818